/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#2e3132',
        'surface-variant': '#e1e2e4',
        'surface-container': '#edeef0',
        tertiary: '#735c00',
        'surface-container-high': '#e7e8ea',
        secondary: '#575e70',
        'primary-fixed-dim': '#62df7d',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#141b2b',
        'surface-container-highest': '#e1e2e4',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error-container': '#93000a',
        outline: '#6e7b6c',
        'tertiary-fixed-dim': '#eec200',
        'on-tertiary-fixed-variant': '#574500',
        surface: '#f8f9fb',
        'on-background': '#191c1e',
        error: '#ba1a1a',
        'inverse-on-surface': '#f0f1f3',
        'surface-container-low': '#f3f4f6',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#5c6274',
        'tertiary-fixed': '#ffe083',
        'secondary-fixed': '#dce2f7',
        'secondary-fixed-dim': '#c0c6db',
        'on-surface': '#191c1e',
        'on-secondary-fixed-variant': '#404758',
        'inverse-primary': '#62df7d',
        'surface-bright': '#f8f9fb',
        background: '#f8f9fb',
        'on-primary-fixed': '#002109',
        primary: '#006b2c',
        'on-primary-fixed-variant': '#005320',
        'on-tertiary-fixed': '#231b00',
        'secondary-container': '#d9dff5',
        'primary-container': '#00873a',
        'on-surface-variant': '#3e4a3d',
        'tertiary-container': '#cea700',
        'error-container': '#ffdad6',
        'surface-tint': '#006e2d',
        'surface-dim': '#d9dadc',
        'on-tertiary-container': '#4e3e00',
        'primary-fixed': '#7ffc97',
        'outline-variant': '#bdcaba',
        'on-primary-container': '#f7fff2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      boxShadow: {
        ambient: '0 12px 32px rgba(25, 28, 30, 0.06)',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #006b2c 0%, #00873a 100%)',
      },
    },
  },
  plugins: [],
};
